parameters:

services:
    acilia.dblogger:
        class: Acilia\Bundle\DBLoggerBundle\Service\DatabaseHandler
        calls:
            - [ setDoctrine, [ "@doctrine" ] ]
            - [ setConfig, [ "%acilia_db_logger%" ] ]

    acilia.dblogger.archive:
        class: Acilia\Bundle\DBLoggerBundle\Command\ArchiveCommand
        arguments: [ '%acilia_db_logger%' ]
        tags:
            - { name: 'console.command' }
        calls:
            - [ setDoctrine, [ "@doctrine" ] ]