parameters:

services:
    acilia.dblogger:
        class: Acilia\Bundle\DBLoggerBundle\Service\DatabaseHandler
        calls:
            - [ setDoctrine, [ "@doctrine" ] ]
            - [ setConfig, [ "%acilia_db_logger%" ] ]